# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'd_principal.ui'
##
## Created by: Qt User Interface Compiler version 6.10.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QGroupBox, QHeaderView,
    QLabel, QLineEdit, QMainWindow, QPushButton,
    QSizePolicy, QSplitter, QTabWidget, QToolBar,
    QToolBox, QTreeView, QTreeWidget, QTreeWidgetItem,
    QVBoxLayout, QWidget)
import ui.menus_rc

class Ui_d_principal(object):
    def setupUi(self, d_principal):
        if not d_principal.objectName():
            d_principal.setObjectName(u"d_principal")
        d_principal.resize(1180, 521)
        self.actionLogon = QAction(d_principal)
        self.actionLogon.setObjectName(u"actionLogon")
        icon = QIcon()
        icon.addFile(u":/png/ico/db_logon.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionLogon.setIcon(icon)
        self.actionLogoff = QAction(d_principal)
        self.actionLogoff.setObjectName(u"actionLogoff")
        icon1 = QIcon()
        icon1.addFile(u":/png/ico/db_logoff.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionLogoff.setIcon(icon1)
        self.actionNewEditor = QAction(d_principal)
        self.actionNewEditor.setObjectName(u"actionNewEditor")
        icon2 = QIcon()
        icon2.addFile(u":/png/ico/file_new.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionNewEditor.setIcon(icon2)
        self.actionSaveEditor = QAction(d_principal)
        self.actionSaveEditor.setObjectName(u"actionSaveEditor")
        icon3 = QIcon()
        icon3.addFile(u":/png/ico/file_saveall.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSaveEditor.setIcon(icon3)
        self.actionOpenEditor = QAction(d_principal)
        self.actionOpenEditor.setObjectName(u"actionOpenEditor")
        icon4 = QIcon()
        icon4.addFile(u":/png/ico/file_open.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionOpenEditor.setIcon(icon4)
        self.actionRunSQL = QAction(d_principal)
        self.actionRunSQL.setObjectName(u"actionRunSQL")
        icon5 = QIcon()
        icon5.addFile(u":/png/ico/sql_run.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionRunSQL.setIcon(icon5)
        self.actionStopSQL = QAction(d_principal)
        self.actionStopSQL.setObjectName(u"actionStopSQL")
        icon6 = QIcon()
        icon6.addFile(u":/png/ico/sql_stop.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionStopSQL.setIcon(icon6)
        self.actionCommit = QAction(d_principal)
        self.actionCommit.setObjectName(u"actionCommit")
        icon7 = QIcon()
        icon7.addFile(u":/png/ico/sql_commit.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionCommit.setIcon(icon7)
        self.actionRollback = QAction(d_principal)
        self.actionRollback.setObjectName(u"actionRollback")
        icon8 = QIcon()
        icon8.addFile(u":/png/ico/sql_rollback.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionRollback.setIcon(icon8)
        self.actionConfigs = QAction(d_principal)
        self.actionConfigs.setObjectName(u"actionConfigs")
        icon9 = QIcon()
        icon9.addFile(u":/png/ico/preferences.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionConfigs.setIcon(icon9)
        self.centralwidget = QWidget(d_principal)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout_3 = QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.splitter = QSplitter(self.centralwidget)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Horizontal)
        self.toolBox = QToolBox(self.splitter)
        self.toolBox.setObjectName(u"toolBox")
        self.toolBox.setMinimumSize(QSize(200, 0))
        self.toolBox.setMaximumSize(QSize(16777215, 16777215))
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.page.setGeometry(QRect(0, 0, 713, 385))
        self.verticalLayout = QVBoxLayout(self.page)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.tree_objetos = QTreeWidget(self.page)
        __qtreewidgetitem = QTreeWidgetItem()
        __qtreewidgetitem.setText(0, u"1");
        self.tree_objetos.setHeaderItem(__qtreewidgetitem)
        self.tree_objetos.setObjectName(u"tree_objetos")
        self.tree_objetos.header().setVisible(False)

        self.verticalLayout.addWidget(self.tree_objetos)

        self.toolBox.addItem(self.page, u"Objects Tree")
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.page_2.setGeometry(QRect(0, 0, 713, 385))
        self.verticalLayout_2 = QVBoxLayout(self.page_2)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.tree_templates = QTreeView(self.page_2)
        self.tree_templates.setObjectName(u"tree_templates")
        self.tree_templates.setAlternatingRowColors(True)

        self.verticalLayout_2.addWidget(self.tree_templates)

        self.toolBox.addItem(self.page_2, u"Templates")
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.page_3.setGeometry(QRect(0, 0, 713, 385))
        self.groupBox = QGroupBox(self.page_3)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 160, 281, 91))
        self.chk_find_match_case = QCheckBox(self.groupBox)
        self.chk_find_match_case.setObjectName(u"chk_find_match_case")
        self.chk_find_match_case.setGeometry(QRect(30, 30, 111, 24))
        self.chk_find_match_whole_word = QCheckBox(self.groupBox)
        self.chk_find_match_whole_word.setObjectName(u"chk_find_match_whole_word")
        self.chk_find_match_whole_word.setGeometry(QRect(30, 60, 151, 24))
        self.bt_find_next = QPushButton(self.page_3)
        self.bt_find_next.setObjectName(u"bt_find_next")
        self.bt_find_next.setGeometry(QRect(10, 300, 101, 26))
        self.bt_find = QPushButton(self.page_3)
        self.bt_find.setObjectName(u"bt_find")
        self.bt_find.setGeometry(QRect(10, 270, 101, 26))
        self.bt_find_replace_all = QPushButton(self.page_3)
        self.bt_find_replace_all.setObjectName(u"bt_find_replace_all")
        self.bt_find_replace_all.setGeometry(QRect(120, 300, 101, 26))
        self.bt_find_replace = QPushButton(self.page_3)
        self.bt_find_replace.setObjectName(u"bt_find_replace")
        self.bt_find_replace.setGeometry(QRect(120, 270, 101, 26))
        self.groupBox_2 = QGroupBox(self.page_3)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 0, 281, 151))
        self.edt_find_replace = QLineEdit(self.groupBox_2)
        self.edt_find_replace.setObjectName(u"edt_find_replace")
        self.edt_find_replace.setGeometry(QRect(10, 100, 261, 26))
        self.label = QLabel(self.groupBox_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 20, 71, 18))
        self.label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.edt_find_text = QLineEdit(self.groupBox_2)
        self.edt_find_text.setObjectName(u"edt_find_text")
        self.edt_find_text.setGeometry(QRect(10, 40, 261, 26))
        self.label_2 = QLabel(self.groupBox_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 80, 81, 18))
        self.label_2.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.toolBox.addItem(self.page_3, u"Find/Replace Text")
        self.splitter.addWidget(self.toolBox)
        self.pc_editor = QTabWidget(self.splitter)
        self.pc_editor.setObjectName(u"pc_editor")
        self.pc_editor.setTabsClosable(True)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.pc_editor.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.pc_editor.addTab(self.tab_2, "")
        self.splitter.addWidget(self.pc_editor)

        self.verticalLayout_3.addWidget(self.splitter)

        d_principal.setCentralWidget(self.centralwidget)
        self.toolBar = QToolBar(d_principal)
        self.toolBar.setObjectName(u"toolBar")
        self.toolBar.setIconSize(QSize(25, 25))
        self.toolBar.setToolButtonStyle(Qt.ToolButtonIconOnly)
        self.toolBar.setFloatable(True)
        d_principal.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolBar)

        self.toolBar.addAction(self.actionLogon)
        self.toolBar.addAction(self.actionLogoff)
        self.toolBar.addAction(self.actionNewEditor)
        self.toolBar.addAction(self.actionSaveEditor)
        self.toolBar.addAction(self.actionOpenEditor)
        self.toolBar.addAction(self.actionRunSQL)
        self.toolBar.addAction(self.actionStopSQL)
        self.toolBar.addAction(self.actionCommit)
        self.toolBar.addAction(self.actionRollback)
        self.toolBar.addAction(self.actionConfigs)

        self.retranslateUi(d_principal)

        self.toolBox.setCurrentIndex(0)
        self.pc_editor.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(d_principal)
    # setupUi

    def retranslateUi(self, d_principal):
        d_principal.setWindowTitle(QCoreApplication.translate("d_principal", u"AlgarSQL", None))
        self.actionLogon.setText(QCoreApplication.translate("d_principal", u"Logon", None))
        self.actionLogoff.setText(QCoreApplication.translate("d_principal", u"Logoff", None))
        self.actionNewEditor.setText(QCoreApplication.translate("d_principal", u"NewEditor", None))
#if QT_CONFIG(shortcut)
        self.actionNewEditor.setShortcut(QCoreApplication.translate("d_principal", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionSaveEditor.setText(QCoreApplication.translate("d_principal", u"SaveEditor", None))
#if QT_CONFIG(shortcut)
        self.actionSaveEditor.setShortcut(QCoreApplication.translate("d_principal", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpenEditor.setText(QCoreApplication.translate("d_principal", u"OpenEditor", None))
#if QT_CONFIG(shortcut)
        self.actionOpenEditor.setShortcut(QCoreApplication.translate("d_principal", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionRunSQL.setText(QCoreApplication.translate("d_principal", u"RunSQL", None))
#if QT_CONFIG(shortcut)
        self.actionRunSQL.setShortcut(QCoreApplication.translate("d_principal", u"F8", None))
#endif // QT_CONFIG(shortcut)
        self.actionStopSQL.setText(QCoreApplication.translate("d_principal", u"StopSQL", None))
        self.actionCommit.setText(QCoreApplication.translate("d_principal", u"Commit", None))
        self.actionRollback.setText(QCoreApplication.translate("d_principal", u"Rollback", None))
        self.actionConfigs.setText(QCoreApplication.translate("d_principal", u"Configs", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), QCoreApplication.translate("d_principal", u"Objects Tree", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), QCoreApplication.translate("d_principal", u"Templates", None))
        self.groupBox.setTitle(QCoreApplication.translate("d_principal", u"Options", None))
        self.chk_find_match_case.setText(QCoreApplication.translate("d_principal", u"Match Case", None))
        self.chk_find_match_whole_word.setText(QCoreApplication.translate("d_principal", u"Match Whole Word", None))
        self.bt_find_next.setText(QCoreApplication.translate("d_principal", u"Find Next", None))
        self.bt_find.setText(QCoreApplication.translate("d_principal", u"Find", None))
        self.bt_find_replace_all.setText(QCoreApplication.translate("d_principal", u"Replace All", None))
        self.bt_find_replace.setText(QCoreApplication.translate("d_principal", u"Replace", None))
        self.groupBox_2.setTitle("")
        self.label.setText(QCoreApplication.translate("d_principal", u"Find Text:", None))
        self.label_2.setText(QCoreApplication.translate("d_principal", u"Replace By:", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), QCoreApplication.translate("d_principal", u"Find/Replace Text", None))
        self.pc_editor.setTabText(self.pc_editor.indexOf(self.tab), QCoreApplication.translate("d_principal", u"Tab 1", None))
        self.pc_editor.setTabText(self.pc_editor.indexOf(self.tab_2), QCoreApplication.translate("d_principal", u"Tab 2", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("d_principal", u"toolBar", None))
    # retranslateUi

